name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Linux amd64/i386
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Add i386 architecture
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update -y

    - name: Grab build-essential
      run: |
        sudo apt-get install build-essential -y
    
    - name: Build
      run: |
        CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o build/snapdrop-linux-amd64 main.go
        CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -o build/snapdrop-linux-amd64 main.go
